spring:
  application:
    name: checkin-system
  datasource:
    url: jdbc:mysql://localhost:3306/checkin_db
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
  main:
    allow-bean-definition-overriding: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml